# PiMarket funding options

# Replace with your actual donation URLs
custom: ["https://playforall.online/pimarket#support"]
github: ""
patreon: ""
open_collective: ""
ko_fi: ""
tidelift: ""
liberapay: ""
buy_me_a_coffee: ""
issuehunt: ""
