name: 🐞 Bug Report
description: Report a problem you encountered in PiMarket
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve **PiMarket**! Please provide as much detail as possible.

  - type: input
    id: environment
    attributes:
      label: 📱 Device & Browser
      description: What system were you using when the bug occurred?
      placeholder: Chrome on Android 13

  - type: textarea
    id: steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Describe exactly how we can trigger the issue.
      placeholder: |
        1. Go to...
        2. Click on...
        3. Scroll to...
        4. See the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Result
      placeholder: I expected it to...

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Result
      placeholder: Instead it did...

  - type: textarea
    id: screenshots
    attributes:
      label: 📷 Screenshots
      description: Paste images here or drag them into the box.
